name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Build binaries
        run: |
          set -euo pipefail
          VERSION="${GITHUB_REF_NAME#v}"
          DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          COMMIT="${GITHUB_SHA::7}"
          LDFLAGS="-s -w -X main.version=${VERSION} -X main.commit=${COMMIT} -X main.date=${DATE}"
          mkdir -p dist
          for GOOS in linux; do
            for GOARCH in amd64 arm64; do
              BIN="temperature-exporter-${GOOS}-${GOARCH}"
              echo "Building $BIN"
              CGO_ENABLED=0 GOOS=$GOOS GOARCH=$GOARCH go build -trimpath -ldflags "$LDFLAGS" -o dist/$BIN ./cmd/temperature-exporter
            done
          done
          (cd dist && sha256sum * > SHA256SUMS)

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/temperature-exporter-*
            dist/SHA256SUMS
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
